baseURL = "https://noboru-murata.github.io/multivariate-analysis"
disablePathToLower = true
languageCode = "en-us"
title = "多変量解析"
theme = "docter"
publishDir = "docs"

[params]
  # the name of your project and a link back to the home page
  home = "多変量解析"
  # A small snippet of text above the sidebar:
  # subtitle = ""

  author = "Noboru Murata"
  author_url= "https://noboru-murata.github.io"

  # Point readers to your repo and invite them to edit pages 
  repo_host = "GitHub"
  repo = "https://github.com/noboru-murata/multivariate-analysis"

  # Add a reference to a logo, which will appear in the top right
  # logourl = ""
  # logoalt = ""

  # Mention your hosting provider 
  hosted_on = "GitHub"
  hosted_on_url= "https://github.com/noboru-murata/multivariate-analysis"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["post"]

  # brand color
  brand_color = "#68be8d"

[markup.goldmark.renderer]
  unsafe = true